### ISSUE TITLE
Failed to execute: in.virit.vwscdn.client.Connection queryRemoteWidgetSet

### ISSUE THREAD

**Issue by mortoza** [viritin/vwscdn#3]
Hi
I am having the following exceptions when trying to compile my Vaadin project (Netbeans 8+ Java 8+Glassfish 4.1):

Aug 15, 2015 12:41:04 PM in.virit.vwscdn.client.Connection queryRemoteWidgetSet
SEVERE: Failed to connect service http://cdn.virit.in/api/compiler/compile
javax.ws.rs.ProcessingException: Unable to invoke request
    at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:287)
    at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:407)
    at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:442)
    at org.jboss.resteasy.client.jaxrs.internal.ClientInvocationBuilder.post(ClientInvocationBuilder.java:201)
    at in.virit.vwscdn.client.Connection.queryRemoteWidgetSet(Connection.java:75)
    at in.virit.vwscdn.VWSCDNMojo.serveFromCDN(VWSCDNMojo.java:243)
    at in.virit.vwscdn.VWSCDNMojo.execute(VWSCDNMojo.java:183)
......
Failed to execute goal in.virit.vwscdn:vwscdn-maven-plugin:1.3.0:generate (default) on project invoicer: Remote widgetset compilation failed:  (no response) -> [Help 1]

Extract from My pom.xml

```
        <plugin>
            <groupId>in.virit.vwscdn</groupId>
            <artifactId>vwscdn-maven-plugin</artifactId>
            <version>1.3.0</version>
            <executions>
                <execution>
                    <phase>generate-sources</phase>
                    <goals>
                        <goal>generate</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
```

Thanks for your help.

Mortoza

**Comment by mstahv** [comment]
Try upgrading your plugin to latest 1.3.4 version.

**Comment by mortoza** [comment]
Hi Matti
Used the latest version 1.3.4 and still have problem. Current issue is as follows. I`m running at localhost though:

Failed to load resource: the server responded with a status of 404 () (00:13:35:923 | error, network)
  at http://localhost:8080/jpa_invoicer_master/VAADIN/widgetsets/com.vaadin.DefaultWidgetSet/com.vaadin.DefaultWidgetSet.nocache.js?1440044015424

**Comment by mstahv** [comment]
For some reason it looks like the auto generated WebListener (in.virit.WidgetSet) is not picked up by your server. Are you using Eclipse? It don't always notice files generated by maven builds and might be left out of your development deployment. Refreshing project after "mvn install" and verifying that the generated files is on build paths might help.

**Comment by mortoza** [comment]
Hi
Im using netbeans 8.01

**Comment by sinaisix** [comment]
Same error here. Version 1.3.4 Vaadin 7.5.1 Java EE 7 Payara Server Full Distribution 14.1.153
